# -*- coding: utf-8 -*-
"""Compare TF-IDF+LR with fine-tune BERT for sentiment classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RL2qq0PN3UI0hdQbVp-b2HwIL1dqJz0G

# **The purpose of this project is to do a comparison between TF-IDF+Logistic Regression with Fine-Tune BERT for sentiment classification on stanfordnlp/imdb dataset from Hugging face**

Project Structure is
1. Import Libraries
2. Load Dataset
3. Train-Test Preparation
4. TF-IDF + Logistic Regression
    - Vectorization
    - Training
    - Prediction
    - Evaluation

5. BERT Fine-Tuning
    - Tokenization
    - Training
    - Prediction
    - Evaluation

6. Custom Review Testing

7. Comparative Analysis
    - Accuracy
    - Precision
    - Recall
    - F1 Score
    - Confusion Matrix
    - Training Time

8. Conclusion

importing Libraries
"""

# Data Handling
import pandas as pd
import numpy as np

# Dataset
from datasets import load_dataset

# Visualization
import matplotlib.pyplot as plt

# Traditional ML
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# Metrics
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# BERT
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)

import torch
import torch.nn.functional as F

import time

"""Load Dataset"""

dataset = load_dataset(
    "stanfordnlp/imdb"
)

"""Process Data"""

X_train = dataset["train"]["text"]
y_train = dataset["train"]["label"]

X_test = dataset["test"]["text"]
y_test = dataset["test"]["label"]

"""# Traditional Machine Learning"""

tfidf = TfidfVectorizer(
    max_features=10000,
    stop_words="english"
)

X_train_tfidf = tfidf.fit_transform(
    X_train
)

X_test_tfidf = tfidf.transform(
    X_test
)

"""Train Logistic Regression"""

start_lr = time.time()

lr_model = LogisticRegression(
    max_iter=1000
)

lr_model.fit(
    X_train_tfidf,
    y_train
)

end_lr = time.time()

lr_training_time = (
    end_lr - start_lr
)

"""Predict"""

lr_predictions = lr_model.predict(
    X_test_tfidf
)

"""Evaluate Logistic regression"""

lr_accuracy = accuracy_score(
    y_test,
    lr_predictions
)

lr_precision = precision_score(
    y_test,
    lr_predictions
)

lr_recall = recall_score(
    y_test,
    lr_predictions
)

lr_f1 = f1_score(
    y_test,
    lr_predictions
)

"""# Fine-Tune BERT

Load Tokenizer
"""

tokenizer = AutoTokenizer.from_pretrained(
    "bert-base-uncased"
)

"""Tokenization


"""

def tokenize_function(examples):

    return tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",
        max_length=256
    )

tokenized_dataset = dataset.map(
    tokenize_function,
    batched=True
)

"""Format Dataset"""

tokenized_dataset = tokenized_dataset.remove_columns(
    ["text"]
)

tokenized_dataset.set_format(
    "torch"
)

"""Load BERT model"""

model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=2
)

"""Metrics Function"""

def compute_metrics(eval_pred):

    logits, labels = eval_pred

    predictions = np.argmax(
        logits,
        axis=-1
    )

    return {

        "accuracy": accuracy_score(
            labels,
            predictions
        ),

        "f1": f1_score(
            labels,
            predictions
        )
    }

"""Training Arguments"""

training_args = TrainingArguments(

    output_dir="./results",

    eval_strategy="epoch",

    save_strategy="epoch",

    learning_rate=2e-5,

    per_device_train_batch_size=8,

    per_device_eval_batch_size=8,

    num_train_epochs=2,

    weight_decay=0.01,

    load_best_model_at_end=True,

    report_to="none"
)

"""Trainer"""

trainer = Trainer(

    model=model,

    args=training_args,

    train_dataset=tokenized_dataset["train"],

    eval_dataset=tokenized_dataset["test"],

    compute_metrics=compute_metrics
)

"""Train BERT"""

import datasets
datasets.config.TORCHVISION_AVAILABLE = False

start_bert = time.time()

trainer.train()

end_bert = time.time()

bert_training_time = (
    end_bert - start_bert
)

"""Evaluate BERT"""

bert_results = trainer.predict(
    tokenized_dataset["test"]
)
bert_predictions = np.argmax(
    bert_results.predictions,
    axis=1
)

"""Metrics"""

bert_accuracy = accuracy_score(
    y_test,
    bert_predictions
)

bert_precision = precision_score(
    y_test,
    bert_predictions
)

bert_recall = recall_score(
    y_test,
    bert_predictions
)

bert_f1 = f1_score(
    y_test,
    bert_predictions
)

"""# Custom Review Testing"""

reviews = [

    "This movie was absolutely amazing.",

    "Worst movie ever made.",

    "The acting was fantastic.",

    "I hated every minute.",

    "A masterpiece of cinema."
]

"""Logistic Regression"""

print("Logistic Regression Predictions")

for review in reviews:

    pred = lr_model.predict(
        tfidf.transform([review])
    )[0]

    print(
        review,
        "->",
        "Positive" if pred else "Negative"
    )

"""BERT"""

print("\nBERT Predictions")

for review in reviews:

    inputs = tokenizer(
        review,
        return_tensors="pt",
        truncation=True,
        padding=True
    ).to(model.device) # Move inputs to the same device as the model

    outputs = model(**inputs)

    pred = torch.argmax(
        outputs.logits,
        dim=1
    ).item()

    print(
        review,
        "->",
        "Positive" if pred else "Negative"
    )

"""Create Comparison table"""

comparison_df = pd.DataFrame({

    "Model":[
        "TF-IDF + Logistic Regression",
        "BERT"
    ],

    "Accuracy":[
        lr_accuracy,
        bert_accuracy
    ],

    "Precision":[
        lr_precision,
        bert_precision
    ],

    "Recall":[
        lr_recall,
        bert_recall
    ],

    "F1 Score":[
        lr_f1,
        bert_f1
    ],

    "Training Time (sec)":[
        lr_training_time,
        bert_training_time
    ]
})

comparison_df

"""Visualisation"""

comparison_df.plot(

    x="Model",

    y=[
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ],

    kind="bar",

    figsize=(10,5)
)

plt.title(
    "BERT vs Logistic Regression"
)

plt.ylabel("Score")

plt.show()